// Generated from the PFP module's manifest by tools/build-coins.mjs.
// Do not edit by hand — add artwork to ../pfp and run `npm run coins`.

export type CoinTier = 'common' | 'uncommon' | 'rare' | 'legendary';

export interface Coin {
  /** File name without extension, and the URL segment for its own page. */
  slug: string;
  name: string;
  tier: CoinTier;
}

/** Rarity tiers, rarest last. `weight` is the chance of drawing that tier. */
export const COIN_TIERS: Record<CoinTier, { label: string; line: string; weight: number }> = {
  common: { label: 'Common', line: 'Epic', weight: 60 },
  uncommon: { label: 'Uncommon', line: 'Meme', weight: 27 },
  rare: { label: 'Rare', line: 'Wild', weight: 11 },
  legendary: { label: 'Legendary', line: 'Jackpot', weight: 2 },
};

export const COIN_TIER_ORDER: CoinTier[] = ['common', 'uncommon', 'rare', 'legendary'];

export const COINS: Coin[] = [
  { slug: 'godface', name: 'Godface', tier: 'common' },
  { slug: 'dark-hodl', name: 'Dark HODL', tier: 'common' },
  { slug: 'coin-burner', name: 'Coin Burner', tier: 'common' },
  { slug: 'comet-rim', name: 'Comet Rim', tier: 'common' },
  { slug: 'black-hole', name: 'Black Hole', tier: 'common' },
  { slug: 'genesis', name: 'Genesis', tier: 'common' },
  { slug: 'planet-rise', name: 'Planet Rise', tier: 'common' },
  { slug: 'meteor-shower', name: 'Meteor Shower', tier: 'common' },
  { slug: 'nebula-walker', name: 'Nebula Walker', tier: 'common' },
  { slug: 'star-reach', name: 'Star Reach', tier: 'common' },
  { slug: 'twin-moons', name: 'Twin Moons', tier: 'common' },
  { slug: 'sentinel', name: 'The Sentinel', tier: 'common' },
  { slug: 'float', name: 'Float', tier: 'common' },
  { slug: 'dark-godface', name: 'Dark Godface', tier: 'common' },
  { slug: 'glow-profile', name: 'Glow Profile', tier: 'common' },
  { slug: 'torch-bearer', name: 'Torch Bearer', tier: 'common' },
  { slug: 'comet-godface', name: 'Comet Godface', tier: 'common' },
  { slug: 'constellation', name: 'Constellation', tier: 'common' },
  { slug: 'eclipse', name: 'Eclipse', tier: 'common' },
  { slug: 'ascend', name: 'Ascend', tier: 'common' },
  { slug: 'aurora', name: 'Aurora', tier: 'common' },
  { slug: 'supernova', name: 'Supernova', tier: 'common' },
  { slug: 'ring-walk', name: 'Ring Walk', tier: 'common' },
  { slug: 'telescope', name: 'Stargazer', tier: 'common' },
  { slug: 'monk', name: 'The Monk', tier: 'common' },
  { slug: 'juggle', name: 'Juggler', tier: 'common' },
  { slug: 'swim', name: 'Nebula Swim', tier: 'common' },
  { slug: 'wormhole', name: 'Wormhole', tier: 'common' },
  { slug: 'asteroid-hop', name: 'Asteroid Hop', tier: 'common' },
  { slug: 'mog', name: 'The Mog', tier: 'uncommon' },
  { slug: 'gigachad', name: 'GigaChad', tier: 'uncommon' },
  { slug: 'thinker', name: 'The 3AM Thinker', tier: 'uncommon' },
  { slug: 'point', name: 'What $IF You?', tier: 'uncommon' },
  { slug: 'quiet-flex', name: 'Quiet Flex', tier: 'uncommon' },
  { slug: 'diamond-hands', name: 'Diamond Hands', tier: 'uncommon' },
  { slug: 'aped-earlier', name: 'Aped Earlier', tier: 'uncommon' },
  { slug: 'hodl', name: 'HODL', tier: 'uncommon' },
  { slug: '3am', name: '3AM', tier: 'uncommon' },
  { slug: 'wen-lambo', name: 'Wen Lambo', tier: 'uncommon' },
  { slug: 'sip', name: 'The Sip', tier: 'uncommon' },
  { slug: 'shrug', name: 'What If?', tier: 'uncommon' },
  { slug: 'facepalm', name: 'Facepalm', tier: 'uncommon' },
  { slug: 'salute', name: 'o7', tier: 'uncommon' },
  { slug: 'handshake', name: 'WAGMI', tier: 'uncommon' },
  { slug: 'popcorn', name: 'Popcorn', tier: 'uncommon' },
  { slug: 'gm', name: 'GM', tier: 'uncommon' },
  { slug: 'gn', name: 'GN', tier: 'uncommon' },
  { slug: 'cope', name: 'Cope', tier: 'uncommon' },
  { slug: 'send-it', name: 'Send It', tier: 'uncommon' },
  { slug: 'rekt', name: 'Rekt', tier: 'uncommon' },
  { slug: 'moon', name: 'Moon', tier: 'uncommon' },
  { slug: 'paper-hands', name: 'Paper Hands', tier: 'uncommon' },
  { slug: 'not-a-rug', name: 'Not A Rug', tier: 'uncommon' },
  { slug: 'based', name: 'Based', tier: 'uncommon' },
  { slug: 'few', name: 'Few Understand', tier: 'uncommon' },
  { slug: 'buy-the-dip', name: 'Buy The Dip', tier: 'uncommon' },
  { slug: 'up-only', name: 'Up Only', tier: 'uncommon' },
  { slug: 'this-is-fine', name: 'This Is Fine', tier: 'rare' },
  { slug: 'galaxy-brain', name: 'Galaxy Brain', tier: 'rare' },
  { slug: 'moon-flag', name: 'Moon Flag', tier: 'rare' },
  { slug: 'microwave', name: 'Microwave Cashcat', tier: 'rare' },
  { slug: 'rocket-rodeo', name: 'Rocket Rodeo', tier: 'rare' },
  { slug: 'kaiju', name: 'Kaiju', tier: 'rare' },
  { slug: 'ufo', name: 'Bull Abduction', tier: 'rare' },
  { slug: 'space-dj', name: 'Space DJ', tier: 'rare' },
  { slug: 'shiba-rider', name: 'Shiba Rider', tier: 'rare' },
  { slug: 'explosion', name: 'Never Looks Back', tier: 'rare' },
  { slug: 'hot-tub', name: 'Hot Tub', tier: 'rare' },
  { slug: 'king', name: 'King of Memecoins', tier: 'rare' },
  { slug: 'its-ok-anon', name: "It's OK Anon", tier: 'rare' },
  { slug: 'ice-cold', name: 'Ice Cold', tier: 'rare' },
  { slug: 'lava-forge', name: 'Lava Forge', tier: 'rare' },
  { slug: 'neon', name: 'Neon', tier: 'rare' },
  { slug: 'whale', name: 'Whale Rider', tier: 'rare' },
  { slug: 'holo', name: 'Holo Foil', tier: 'rare' },
  { slug: 'blood-moon', name: 'Blood Moon', tier: 'rare' },
  { slug: 'sunset', name: 'Sunset', tier: 'rare' },
  { slug: 'thunder', name: 'Thunder God', tier: 'rare' },
  { slug: 'sakura', name: 'Sakura', tier: 'rare' },
  { slug: 'campfire', name: 'Moon Camp', tier: 'rare' },
  { slug: 'arcade', name: 'High Score', tier: 'rare' },
  { slug: 'snow-globe', name: 'Snow Globe', tier: 'rare' },
  { slug: 'matrix', name: 'The Matrix', tier: 'rare' },
  { slug: 'chrome', name: 'Chrome', tier: 'rare' },
  { slug: 'cowboy', name: 'Moon Lasso', tier: 'rare' },
  { slug: 'fishing', name: 'Gone Fishing', tier: 'rare' },
  { slug: 'chess', name: 'Checkmate', tier: 'rare' },
  { slug: 'candle-surf', name: 'Candle Surf', tier: 'rare' },
  { slug: 'atlas', name: 'Atlas', tier: 'rare' },
  { slug: 'bear-wrestle', name: 'Bear Market', tier: 'rare' },
  { slug: 'cloud', name: 'Sweet Dreams', tier: 'rare' },
  { slug: 'pizza', name: 'Pizza Run', tier: 'rare' },
  { slug: 'coin-rain', name: 'Coin Rain', tier: 'rare' },
  { slug: 'bull-carry', name: 'Bull Carry', tier: 'rare' },
  { slug: 'pirate', name: 'Captain IF', tier: 'rare' },
  { slug: 'gold-bite', name: 'Gold Bite', tier: 'legendary' },
  { slug: 'gold-throne', name: '1 of 1 Throne', tier: 'legendary' },
  { slug: 'gold-genesis', name: 'Gold Genesis', tier: 'legendary' },
  { slug: 'gold-crown', name: 'Gold Crown', tier: 'legendary' },
  { slug: 'gold-brain', name: 'Gold Galaxy Brain', tier: 'legendary' },
  { slug: 'found-it', name: 'Found It', tier: 'legendary' },
  { slug: 'fork', name: 'The Fork', tier: 'legendary' },
  { slug: 'void', name: 'Void', tier: 'legendary' },
  { slug: 'banknote', name: 'Banknote', tier: 'rare' },
  { slug: 'frame-breaker', name: 'Frame Breaker', tier: 'rare' },
  { slug: 'cutaway', name: 'Cutaway', tier: 'rare' },
  { slug: 'prism', name: 'Prism', tier: 'rare' },
  { slug: 'oilslick', name: 'Oil Slick', tier: 'rare' },
  { slug: 'stained-glass', name: 'Stained Glass', tier: 'uncommon' },
  { slug: 'macro-eye', name: 'Macro Eye', tier: 'uncommon' },
  { slug: 'aurora-ridge', name: 'Aurora Ridge', tier: 'uncommon' },
  { slug: 'thermal', name: 'Thermal', tier: 'uncommon' },
  { slug: 'colour-door', name: 'Colour Door', tier: 'uncommon' },
  { slug: 'pixel', name: 'Pixel', tier: 'common' },
  { slug: 'ukiyo', name: 'Ukiyo', tier: 'common' },
  { slug: 'vaporwave', name: 'Vaporwave', tier: 'common' },
  { slug: 'diorama', name: 'Diorama', tier: 'common' },
  { slug: 'corkboard', name: 'Corkboard', tier: 'rare' },
  { slug: 'trendlines', name: 'Trendlines', tier: 'rare' },
  { slug: 'crayon', name: 'Crayon', tier: 'uncommon' },
  { slug: 'cave', name: 'The Cave', tier: 'uncommon' },
  { slug: 'tinfoil', name: 'Tinfoil', tier: 'uncommon' },
  { slug: 'whiteboard', name: 'Whiteboard', tier: 'uncommon' },
  { slug: 'touch-grass', name: 'Touch Grass', tier: 'common' },
  { slug: 'caffeine', name: 'Caffeine', tier: 'common' },
  { slug: 'ramen', name: 'Ramen', tier: 'common' },
  { slug: 'refresh-finger', name: 'Refresh Finger', tier: 'common' },
  { slug: 'zoom-out', name: 'Zoom Out', tier: 'common' },
  { slug: 'copium', name: 'Copium', tier: 'uncommon' },
  { slug: 'bag-holder', name: 'Bag Holder', tier: 'common' },
  { slug: 'diamond-hands-lit', name: 'Diamond Hands', tier: 'rare' },
  { slug: 'paper-hands-lit', name: 'Paper Hands', tier: 'uncommon' },
  { slug: 'dip-diver', name: 'Dip Diver', tier: 'rare' },
  { slug: 'keyboard-nap', name: 'Keyboard Nap', tier: 'common' },
  { slug: 'napkin-thesis', name: 'Napkin Thesis', tier: 'uncommon' },
  { slug: 'vitruvian', name: 'Vitruvian', tier: 'rare' },
  { slug: 'rushmore', name: 'Rushmore', tier: 'legendary' },
  { slug: 'terracotta', name: 'Terracotta', tier: 'rare' },
  { slug: 'moai', name: 'Moai', tier: 'rare' },
  { slug: 'oil-portrait', name: 'Oil Portrait', tier: 'rare' },
  { slug: 'cave-painting', name: 'Cave Painting', tier: 'uncommon' },
  { slug: 'tapestry', name: 'Tapestry', tier: 'rare' },
  { slug: 'butterfly', name: 'Butterfly', tier: 'rare' },
  { slug: 'schrodinger', name: 'Schrodinger', tier: 'uncommon' },
  { slug: 'mirror-maze', name: 'Mirror Maze', tier: 'legendary' },
  { slug: 'ouroboros', name: 'Ouroboros', tier: 'legendary' },
  { slug: 'iceberg', name: 'Iceberg', tier: 'uncommon' },
  { slug: 'vending', name: 'Vending', tier: 'uncommon' },
  { slug: 'lottery', name: 'Lottery', tier: 'common' },
  { slug: 'fortune', name: 'Fortune', tier: 'rare' },
];
