// Generated by tools/build-coin-history.mjs — do not edit by hand.
// The dataset itself lives in public/machine/ and is fetched by the page;
// this file records only what the build produced.

export const HISTORY_CAPTURED = '2026-08-31';
export const HISTORY_COIN_COUNT = 781;
