// Generated by tools/build-holders.mjs — do not edit by hand.
// Run `npm run holders` to refresh. Read from the block explorer, which the
// browser cannot call directly: it is behind a challenge and sends no CORS header.

/** What an address is, when that can be established from the chain. */
export type HolderKind = 'burn' | 'pool' | 'contract' | 'unknown';

export interface Holder {
  address: string;
  /** Whole $IF, floored. */
  tokens: number;
  kind: HolderKind;
}

/** Largest first. */
export const HOLDERS: Holder[] = [
  {
    address: '0x000000000000000000000000000000000000dEaD',
    tokens: 93734842,
    kind: 'burn',
  },
  {
    address: '0xE36B1A9D671Da4ee14a42991B0f010A81466d05a',
    tokens: 31157590,
    kind: 'unknown',
  },
  {
    address: '0xb64325a69cCD29C54b7d9e70b0F306fa9B2b2697',
    tokens: 22580002,
    kind: 'contract',
  },
  {
    address: '0x39A200271525E9641e799127bdAB299DAeF21953',
    tokens: 16323394,
    kind: 'pool',
  },
  {
    address: '0x1bF457573fAec8F6eB90A23BF8a149107D0Af6Bc',
    tokens: 15909138,
    kind: 'contract',
  },
  {
    address: '0x0042Bc9E0fDDD670DC1BAE45bDbBf19CAC384C34',
    tokens: 15631454,
    kind: 'unknown',
  },
  {
    address: '0x71f2F1c2dc94cDaBFE29Cb355119f8683AE0969b',
    tokens: 14468370,
    kind: 'unknown',
  },
  {
    address: '0x2eB50B5FA36896B556090B26b4b600887cc513D8',
    tokens: 13841693,
    kind: 'unknown',
  },
  {
    address: '0x918FCe7Ee04C2f353746e571b4ddA2E663fE0735',
    tokens: 12600460,
    kind: 'contract',
  },
  {
    address: '0xcAF284Fd315322b02bAEb9c8116883F1Dd20497d',
    tokens: 12493412,
    kind: 'unknown',
  },
  {
    address: '0x43F2613C1E3C0305D6CC4f6a2905Eed456b7C195',
    tokens: 9533468,
    kind: 'unknown',
  },
  {
    address: '0x8EfC646EbE93feeBfDBd36359BeCfC62716d244e',
    tokens: 9274632,
    kind: 'contract',
  },
  {
    address: '0x7Ff8bbf9C8AB106db589e7863fb100525F61CCe5',
    tokens: 9062233,
    kind: 'unknown',
  },
  {
    address: '0xA24509fdcCa6CE6dA70A81152c7d075529653D8C',
    tokens: 9037927,
    kind: 'unknown',
  },
  {
    address: '0x5C7cE035FbE426e7B2182B7165e1cD47834a056b',
    tokens: 9037367,
    kind: 'unknown',
  },
];

/** When this list was read, as YYYY-MM-DD. */
export const HOLDERS_CAPTURED = '2026-09-04';
