// Generated by tools/build-tweets.mjs — do not edit by hand.
// Add URLs to src/config/tweets.ts and run `npm run tweets`.

export interface TweetCard {
  /** Plain text. Never markup — see the note in tools/build-tweets.mjs. */
  text: string;
  authorName: string;
  authorUrl: string;
  url: string;
}

export const TWEET_CARDS: TweetCard[] = [];
