// Generated by tools/build-tweets.mjs — do not edit by hand.
// Add URLs to src/config/tweets.ts and run `npm run tweets`.

export interface TweetCardPhoto {
  src: string;
  width: number;
  height: number;
}

export interface TweetCard {
  text: string;
  authorName: string;
  /** Without the @. */
  authorHandle: string;
  /** Served from our own origin, or absent when it could not be fetched. */
  avatar?: string;
  /** YYYY-MM-DD. */
  postedAt: string;
  photos: TweetCardPhoto[];
  url: string;
}

export const TWEET_CARDS: TweetCard[] = [
  {
    text: "You stop telling people. You don't stop holding.",
    authorName: 'What $IF on Robinhood Chain',
    authorHandle: 'WhatIFonHOOD',
    avatar: '/posts/2094772271722434583-avatar.webp',
    postedAt: '2026-09-01',
    photos: [
      {
        src: '/posts/2094772271722434583-1.webp',
        width: 1200,
        height: 1200,
      },
    ],
    url: 'https://x.com/WhatIFonHOOD/status/2094772271722434583',
  },
  {
    text: 'Just one. What $IF?',
    authorName: 'What $IF on Robinhood Chain',
    authorHandle: 'WhatIFonHOOD',
    avatar: '/posts/2094394783137677653-avatar.webp',
    postedAt: '2026-08-31',
    photos: [
      {
        src: '/posts/2094394783137677653-1.webp',
        width: 1200,
        height: 670,
      },
    ],
    url: 'https://x.com/WhatIFonHOOD/status/2094394783137677653',
  },
  {
    text: "$IF you're in the $HOOD , help your brothers make it to right timeline.",
    authorName: 'What $IF on Robinhood Chain',
    authorHandle: 'WhatIFonHOOD',
    avatar: '/posts/2093803407362625946-avatar.webp',
    postedAt: '2026-08-29',
    photos: [
      {
        src: '/posts/2093803407362625946-1.webp',
        width: 1200,
        height: 1200,
      },
    ],
    url: 'https://x.com/WhatIFonHOOD/status/2093803407362625946',
  },
  {
    text: 'What $IF I told you...\n\nThe answer is already drawn in the sand?',
    authorName: 'What $IF on Robinhood Chain',
    authorHandle: 'WhatIFonHOOD',
    avatar: '/posts/2089569584860799369-avatar.webp',
    postedAt: '2026-08-18',
    photos: [
      {
        src: '/posts/2089569584860799369-1.webp',
        width: 1200,
        height: 800,
      },
    ],
    url: 'https://x.com/WhatIFonHOOD/status/2089569584860799369',
  },
];
