// Generated by tools/build-tweets.mjs — do not edit by hand.
// Add URLs to src/config/tweets.ts and run `npm run tweets`.

export interface TweetCard {
  /** Plain text. Never markup — see the note in tools/build-tweets.mjs. */
  text: string;
  authorName: string;
  authorUrl: string;
  url: string;
}

export const TWEET_CARDS: TweetCard[] = [
  {
    "text": "What $IF @RobinhoodCrypto eventually lists the native meme of its own ecosystem?",
    "authorName": "What $IF on Robinhood Chain",
    "authorUrl": "https://x.com/WhatIFonHOOD",
    "url": "https://x.com/WhatIFonHOOD/status/2094442732940927202"
  },
  {
    "text": "Just one. What $IF?",
    "authorName": "What $IF on Robinhood Chain",
    "authorUrl": "https://x.com/WhatIFonHOOD",
    "url": "https://x.com/WhatIFonHOOD/status/2094394783137677653"
  },
  {
    "text": "$IF you're in the $HOOD , help your brothers make it to right timeline.",
    "authorName": "What $IF on Robinhood Chain",
    "authorUrl": "https://x.com/WhatIFonHOOD",
    "url": "https://x.com/WhatIFonHOOD/status/2093803407362625946"
  }
];
