import type { SiteCopy } from './types.ts';

export const tr: SiteCopy = {
  htmlLang: 'tr',

  nav: {
    links: [
      { label: 'Fikir', href: '#thesis' },
      { label: 'Rakamlar', href: '#numbers' },
      { label: 'Nasıl alınır', href: '#buy' },
      { label: 'SSS', href: '#faq' },
    ],
    toolsLabel: 'Araçlar',
    tools: {
      ask: { label: 'Daha iyi bir soru sor', blurb: 'Merak etmenin bir milyon yolu' },
      pfp: { label: 'Kendi paranı bul', blurb: 'Dört nadirlik, biri senin' },
      memes: { label: 'Kasa', blurb: 'Çalması serbest' },
      stats: { label: 'Veriler', blurb: 'Her rakam canlı' },
      holdings: { label: 'Cüzdan sorgusu', blurb: 'Bağlantı gerekmez' },
      learn: { label: 'Öğren', blurb: 'Güvenlik, temeller ve kanıt' },
      docs: { label: 'Teknik doküman', blurb: 'Her şey, yazılı hâlde' },
      roadmap: { label: 'Güncellemeler', blurb: 'En yenisi en üstte' },
      brand: { label: 'Marka', blurb: 'Logolar ve görseller' },
    },
    toolGroups: { data: 'Rakamlar', play: 'Oyna', assets: 'Görseller', read: 'Oku' },
    languageMenu: 'Dil',
    buy: '$IF Al',
    home: 'What $IF — ana sayfa',
    pfp: 'Kendi paranı bul',
    openMenu: 'Menüyü aç',
    closeMenu: 'Menüyü kapat',
    languageLabel: 'Dil',
  },

  hero: {
    liveOn: 'Robinhood Chain üzerinde yayında',
    titleLead: 'Ya',
    titleTail: 'bu o ise?',
    description:
      'Sonsuz meraklılar için bir meme coin. Ya daha önce alsaydın? Ya elinde tutsaydın? Ya bu gerçekten o ise?',
    buy: '$IF Al',
    chart: 'Grafik',
  },

  posts: {
    eyebrow: 'Akıştan',
    readOnX: 'X’te oku',
    heading: { lead: 'İnsanlar hâlâ', accent: 'soruyor.' },
    intro: 'Topluluğun paylaştıkları. Gömülmüyor, burada çiziliyor — takip kodu yok, iframe yok.',
    follow: "X'te takip et",
  },

  marquee: [
    'Ya $IF',
    'daha önce alsaydın?',
    'Ya',
    'elinde tutsaydın?',
    'Ya',
    'bu o ise?',
    'Ya',
    'hiç satmasaydık?',
    'Ya',
    'bir milyara ulaşırsa?',
  ],

  cosmic: {
    kicker: 'Ya',
    statements: [
      'Ya bir hayat kurtarabilseydim?',
      'Ya bir dilekle kanseri yenebilseydim?',
      'Ya aşk hepimizden uzun yaşasaydı?',
      'Ya tek bir ses bir savaşı bitirebilseydi?',
      'Ya kırılanlar inşa edenler olsaydı?',
      'Ya umut hiç yalan olmasaydı?',
      'Ya bir çocuğun hayali yarını yeniden yazsaydı?',
      'Ya merhamet güçten daha kuvvetli olsaydı?',
      'Ya her ismi hatırlasaydık?',
      'Ya en karanlık gece şafağı saklasaydı?',
      'Ya affetmek çare olsaydı?',
      'Ya kimse yalnız yas tutmasaydı?',
    ],
  },

  thesis: {
    eyebrow: 'Fikir',
    heading: { lead: 'Tek bir soru.', accent: 'Sonsuz ihtimal.' },
    intro:
      '$IF bir fayda tokeni değil, yönetişim tokeni de değil. Herkesin gece 3’te aklına gelen o düşüncenin, oyundaki en yeni zincire kazınmış hâli.',
    pillars: [
      {
        title: 'Her şey bir soruyla başlar',
        body: 'Pişman olduğun her işlem “ya olsaydı?” ile başladı. $IF bu soruyu zincire yazacak kadar ciddiye alıyor.',
      },
      {
        title: 'Robinhood Chain üzerine kurulu',
        body: 'Hızlı bloklar, ucuz gas ve bir nesli piyasaya çeken isim. Robinhood da bir “ya olsaydı” olarak başlamıştı.',
      },
      {
        title: 'Yüzde dokuzu şimdiden gitti',
        body: '{burned} $IF, anahtarı kimsede olmayan bir yakma adresinde duruyor. Bu bir söz değil — kendi gözünle okuyabileceğin bir bakiye.',
      },
      {
        title: 'Her şeyi kendin doğrula',
        body: 'Kontrat, havuz, yakılan miktar ve cüzdan sayısı tamamen açık; hepsine link verdik. Hiçbir siteye güvenme — buna dâhil.',
      },
    ],
  },

  numbers: {
    eyebrow: 'Rakamlar',
    heading: { lead: 'Hile yok.', accent: 'Sadece matematik.' },
    intro:
      'Bir milyar token, açık bir kontrat ve herkesin denetleyebileceği bir yakma adresi. Bu bölümün kısa olmasının sebebi bu.',
    contractLabel: 'Kontrat adresi',
    verifyNote: 'Almadan önce her karakteri X ve Telegram hesabımızdakiyle karşılaştır.',
    copy: 'Kopyala',
    copied: 'Kopyalandı',
    viewOnExplorer: "Blockscout'ta gör",
    stats: {
      price: 'Fiyat',
      marketCap: 'Piyasa değeri',
      liquidity: 'Likidite',
      volume: '24s hacim',
      supply: 'Toplam arz',
      burned: 'Yakılan',
      holders: 'Cüzdan',
      chain: 'Zincir',
    },
    burnHeadline: 'yakıldı ve geri alınamaz',
    burnBody:
      'Özel anahtarı olmayan 0x…dEaD adresine gönderildi. Bu tokenleri kimse kıpırdatamaz — ekip de, sen de, hiç kimse.',
    asOf: 'şu tarihte',
    live: 'Canlı',
  },

  buy: {
    eyebrow: 'Çantanı doldur',
    heading: { lead: 'Üç adım.', accent: 'Hepsi bu.' },
    intro:
      'Bir cüzdana, Robinhood Chain üzerinde biraz ETH’ye ve otuz saniyeye ihtiyacın var. Tamamı aşağıda.',
    steps: [
      {
        title: 'Bir cüzdan edin',
        body: 'Bilgisayarda MetaMask, OKX veya Trust; telefonda Robinhood Wallet. Robinhood Chain’i kullanan bir sayfayı ilk açtığında cüzdanın ağı eklemeyi kendisi önerecek.',
        action: 'MetaMask edin',
      },
      {
        title: "Robinhood Chain'e ETH getir",
        body: 'Robinhood uygulamasından ETH çek ve ağ olarak Robinhood Chain’i seç. ETH’in başka bir zincirde mi? Robinhood köprü yollarını kendi dokümanlarında yayınlıyor.',
        action: 'Köprüleme rehberi',
      },
      {
        title: "Uniswap'ta takas et",
        body: 'Robinhood Chain üzerinde $IF önceden seçili olarak açılır. Onaylamadan önce oradaki adresi yukarıdakiyle karşılaştır.',
        action: "Uniswap'ta takas et",
      },
    ],
    venuesTitle: 'Takip et, grafiğe bak, doğrula',
    venues: [
      { label: 'Uniswap', blurb: 'Ana IF/WETH havuzu.' },
      { label: 'DexScreener', blurb: 'Canlı fiyat ve likidite.' },
      { label: 'CoinGecko', blurb: 'Piyasa verisi ve geçmiş.' },
      { label: 'CoinMarketCap', blurb: 'Sıralama ve arz.' },
      { label: 'Blockscout', blurb: 'Kontratın kendisi.' },
    ],
    safetyNote:
      'Bu site senden asla cüzdan bağlamanı, bir mesaj imzalamanı veya kurtarma kelimelerini girmeni istemez. $IF olduğunu söyleyip bunu isteyen bir sayfa varsa, o biz değiliz.',
  },

  pfpTeaser: {
    eyebrow: 'Havuz',
    heading: { lead: 'Sana ait olan', accent: 'parayı bul.' },
    body: 'El yapımı $IF paraları, dört nadirlik seviyesi. Bir kez dokun, kendininkini al, profil fotoğrafın yap. Cüzdan yok, kayıt yok, bağlanacak hiçbir şey yok.',
    cta: 'Üreteci aç',
  },

  vaultTeaser: {
    eyebrow: 'Kasa',
    heading: { lead: 'Her meme.', accent: 'Çalması serbest.' },
    body: 'Yaptığımız her meme, tam çözünürlükte, paylaşmaya hazır. Zaten bunun için varlar. Sağ tıkla, sorumluca.',
    cta: 'Kasayı aç',
  },

  roadmap: {
    eyebrow: 'Yatırımcılar sorup duruyor',
    heading: { lead: 'Peki…', accent: 'yol haritası?' },
    fileName: 'if_roadmap_final_v3.pdf',
    lastEdited: '1 sayfa · son düzenleme: hiçbir zaman',
    quarters: [
      'Ç1 — ya olsaydı',
      'Ç2 — ya olsaydı',
      'Ç3 — hâlâ soruyoruz',
      'Ç4 — meme, muhtemelen',
    ],
    stamp: 'Hâlâ soruyoruz.',
    footnote: 'Yol haritası yok. Fayda yok. Söz yok. Yalnızca eğlence amaçlıdır.',
  },

  faq: {
    eyebrow: 'Aptalca soru yoktur',
    heading: { lead: 'Sorular,', accent: 'yanıtlandı.' },
    items: [
      {
        q: '$IF nedir?',
        a: '$IF, Robinhood Chain üzerinde, her yatırımcının gece 3’te kendine sorduğu tek soru etrafında kurulmuş bir meme coin: ya olsaydı? Ürün yol haritası yok, fayda vaadi yok. Bir soru, bir topluluk ve bir grafik var.',
      },
      {
        q: "Robinhood Chain'e ETH nasıl getirilir?",
        a: 'Yeni başlayanların çoğu burada takılıyor. En basit yol, Robinhood uygulamasından ETH çekip ağ olarak Robinhood Chain’i seçmek. ETH’in başka bir zincirdeyse, ona ulaşan köprüleri Robinhood kendi dokümanlarında listeliyor. Her hâlükârda gas için biraz ETH bırak.',
      },
      {
        q: 'Nereden alınır?',
        a: 'Robinhood Chain üzerindeki Uniswap’tan, bu sayfadaki kontrat adresini kullanarak. En derin piyasa IF/WETH havuzu. Adresi mutlaka karakter karakter karşılaştır — meme coin’ler taklitçi çeker ve tek bir yanlış karakter paranı bir yabancıya gönderir.',
      },
      {
        q: 'Doğru tokeni aldığımı nasıl anlarım?',
        a: 'Yayınlayacağımız tek adres 0x232CDFc415D10b673845D83Dc02ba2eaBe7e30d1 ve bu sayfada, X profilimizde ve Telegram’ımızda tam hâliyle görünür. Bir site sana kısaltılmış ya da farklı bir adres gösteriyorsa, kapat.',
      },
      {
        q: 'Vergi var mı?',
        a: '$IF kontratı işlemenin üstüne hiçbir şey eklemiyor. Ana havuzda göreceğin %1, Uniswap’ın kendi komisyon kademesidir ve likidite sağlayanlara gider, bize değil. Kontrat Blockscout’ta açık — bir sitenin sözüne güvenmek yerine kendin oku.',
      },
      {
        q: 'Ne kadarı yakıldı?',
        a: '{burned} $IF — toplam arzın {burnedPercent}’i — özel anahtarı olmayan 0x…dEaD adresinde duruyor. Bu tokenler bir daha asla hareket edemez. Bu, bir belgedeki iddia değil, blok gezgininde canlı duran bir bakiye.',
      },
      {
        q: 'Topluluk nerede?',
        a: 'X: @WhatIFonHOOD, Telegram: t.me/WhatIFonHoodChain. İkisi de aktif ve ikisini de parayı tutan insanlar yürütüyor. Herkes geliştiricidir.',
      },
      {
        q: '$IF bir yatırım mı?',
        a: 'Hayır. İçsel değeri, ekip vaadi ve yol haritası olmayan bir meme coin. Fiyat yükseldiği kadar kolay düşer ve meme coin’lerin çoğu sıfırda biter. Tamamını kaybetmeyi rahatça göze alamayacağın bir miktarı asla koyma.',
      },
    ],
  },

  footer: {
    heading: { lead: 'Ya', accent: 'katılsaydın?' },
    subtitle: 'Grafik orada. Soru burada.',
    buy: '$IF Al',
    telegram: "Telegram'a katıl",
    follow: "X'te takip et",
    chart: 'Grafik',
    canonical: 'Tek resmî site whatifonhood.com. Geri kalan her şey başkasına ait.',
    disclaimer:
      '$IF, içsel değeri olmayan ve finansal getiri beklentisi taşımayan bir meme coin’dir. Buradaki hiçbir şey yatırım tavsiyesi değildir. Kendi araştırmanı yap.',
    builtBy: 'Herkes geliştiricidir.',
  },

  pages: {
    memes: {
      title: 'Kasa',
      heading: { lead: 'Her meme.', accent: 'Çalması serbest.' },
      intro:
        'Her $IF meme’i, tam çözünürlükte, filigransız, atıf gerekmeden. Paylaş, bastır, yeniden karıştır. Zaten bunun için varlar.',
      download: 'İndir',
      all: 'Hepsi',
      searchLabel: 'Meme ara',
      empty: 'Eşleşen bir şey yok. Başka bir kelime dene.',
      count: 'meme',
    },
    brand: {
      title: 'Marka',
      heading: { lead: 'İşaretler', accent: 've kullanımı.' },
      intro:
        'Tek marka, üç işaret: para tokeni, karakter dünyayı, kelime işareti ismi tanımlar. Neye ihtiyacın varsa al.',
      download: 'İndir',
      kitNote:
        'Logolar, avatar, vektör kelime işaretleri, bannerlar, karakter referans sayfası ve şeffaf pozlar — palet, tipografi ve kurallar bir readme dosyasında.',
      rulesTitle: 'Önemli üç şey',
      rules: [
        'Para her zaman kenar çerçevesini korur. Onu para gibi gösteren şey odur.',
        'Kontrat adresini asla bir başlık fontuyla dizme ve asla kısaltma.',
        'Robinhood tüyü kullanılmaz. Yerine “on Robinhood Chain” yaz.',
      ],
    },
    stats: {
      title: 'Veriler',
      heading: { lead: 'Her rakam,', accent: 'canlı.' },
      intro: 'Fiyat, likidite, arz ve yakılanlar — doğrudan Robinhood Chain’den.',
      sourceNote:
        'Fiyat, likidite ve hacim DexScreener’dan; sahipler ve yoğunlaşma GeckoTerminal’den; yakım doğrudan zincirden okunuyor. Bu sekme açık olduğu sürece her şey kendiliğinden yenilenir.',
      poolLabel: 'Ana havuz',
      openExplorer: 'Kontratı aç',
      openChart: 'Grafiği aç',
      timeframes: { day: '24S', week: '7G', month: '30G', quarter: '90D', all: 'TÜMÜ' },
      resizeChart: 'Grafiği yeniden boyutlandırmak için sürükle',
      zoomIn: 'Yakınlaştır',
      zoomOut: 'Uzaklaştır',
      resetZoom: 'Sıfırla',
      average: 'Ort.',
      ema: 'EMA',
      chartHint: 'Yakınlaştırmak için kaydır · taşımak için sürükle · sıfırlamak için çift tıkla',
      chartTypes: { candles: 'Mum', line: 'Çizgi' },
      logScale: 'Log',
      chartTitle: 'Fiyat',
      feedTitle: 'Son işlemler',
      biggestBuy: 'En büyük alım',
      buys: 'Alım',
      sells: 'Satım',
      buyLabel: 'Alım',
      sellLabel: 'Satım',
      viewTx: 'Gör',
      loading: 'Zincir okunuyor…',
      failed: 'Piyasa verisine şu an ulaşılamadı. Yukarıdaki rakamlar son derlemeden geliyor.',
      feedNote: 'IF/WETH havuzundaki en son işlemler.',
      biggestSell: 'En büyük satış',
      windowHours: 'son {hours} saat içinde',
      holdersTitle: 'Sahipler',
      concentration: 'Kimin elinde',
      bands: { top10: 'İlk 10', next20: '11–30', next20More: '31–50', rest: 'Diğer herkes' },
      holdersUpdated: 'yeniden sayıldı',
      pressureTitle: 'Alım ve satım baskısı',
      pressureNote:
        'Son bir günün saatlik hacmi, 500 dolar ve üzeri işlemler. Alımlar yukarı, satışlar aşağı.',
      burnHistoryTitle: 'Her yakım',
      burnHistoryNote: 'Zincirden okundu. Her basamak açabileceğin bir işlem.',
      reproduceTitle: 'Her rakamı kendin kontrol et',
      reproduceIntro:
        'Bu sayfadaki her rakam herkese açık, anahtarsız, salt okunur bir çağrıdan geliyor. Her biri, tam olarak bizim yaptığımız hâliyle aşağıda. Herhangi birini bir terminale yapıştırın.',
      reproduceField: 'Rakamın yeri',
      reproduceNote:
        'Bunlar sayfanın kendi kullandığı adres ve uç noktalardan üretilir, dolayısıyla sessizce uyumsuz hâle gelemezler. Biri yukarıda gördüğünüzle çelişiyorsa sayfa yanlıştır ve bunu bilmek isteriz.',
      reproduceLabels: {
        price: 'Fiyat',
        marketCap: 'Piyasa değeri',
        liquidity: 'Likidite',
        volume: '24 saatlik hacim',
        holders: 'Sahip sayısı',
        burned: 'Yakılan token',
        supply: 'Toplam arz',
        owner: 'Sözleşmeyi kim değiştirebilir',
        trades: 'Son işlemler',
        holderList: 'En büyük sahipler',
      },
      weekTitle: 'Son yedi gün',
      weekPrice: 'Fiyat',
      weekBurned: 'Yakıldı',
      weekBurnCount: '{count} yakım boyunca',
      weekLargest: 'En büyük tek yakım',
      weekNote: '{date} tarihine kadar. Günlük yenilenir, canlı değil — yukarıdaki rakamlar canlı.',
      holderTableTitle: 'Kim tutuyor',
      holderTableIntro:
        'En büyük on beş bakiye, tespit edilebilen her şey adlandırılmış. En büyüğü yakım adresi — o tokenlar tutulmuyor, yok edilmiş.',
      holderTableNote: 'Blok gezgininden {date} tarihinde okundu. Her satır adrese bağlanır.',
      holderAddress: 'Adres',
      holderWhat: 'Nedir',
      holderTokens: 'Token',
      holderShare: 'Arzdaki payı',
      holderKinds: { burn: 'Yakıldı', pool: 'Likidite havuzu', contract: 'Sözleşme', unknown: '—' },
      biggestBurnsTitle: 'En büyük on yakım',
      sinceLead: 'Son ziyaretinden bu yana, {ago}',
      sincePrice: 'Fiyat {change} hareket etti, {price} oldu.',
      sinceBurned: '{amount} $IF yakıldı.',
      sinceHolders: 'Sahip sayısı {change} değişti, {total} oldu.',
      sinceNothing: 'Pek bir şey yok. Hâlâ soruyoruz.',
      trustTitle: 'Herkesin yapabileceği kontroller',
      trustNote:
        'Bunlardan ikisi bizim değil, üçüncü tarafların beyanıdır; diğer üçü bu sayfa yüklenirken doğrudan sözleşmeden okunur. Her biri kendiniz kontrol edebileceğiniz yere bağlanır ve okunamayan bir kontrol, geçti göstermek yerine bunu söyler.',
      checks: {
        verified: 'Listeleme doğrulandı',
        honeypot: 'Honeypot kontrolü',
        supply: 'Sabit arz, mint fonksiyonu yok',
        burn: 'Yakım adresinin özel anahtarı yok',
        owner: 'Sözleşmeyi kim değiştirebilir',
      },
      checkPass: 'Geçti',
      burnMark: '{amount} yakıldı',
      ownerNone: 'Owner fonksiyonu yok',
      ownerSome: 'Sahibi',
    },
    pfp: {
      title: 'PFP Üretici',
      heading: { lead: 'Sana ait olan', accent: 'parayı bul.' },
      intro:
        "Üret'e bas, bir $IF parası al, profil fotoğrafın yap. Cüzdan yok, kayıt yok, bağlanacak hiçbir şey yok.",
      subline: 'Dört nadirlik. Her çekiliş ücretsiz.',
      generate: "$IF'imi üret",
      again: 'Tekrar',
      hint: 'Tek dokunuş. Hiçbir şey kendi tarayıcının dışına çıkmaz.',
      tiers: { common: 'Sıradan', uncommon: 'Az bulunur', rare: 'Nadir', legendary: 'Efsanevi' },
      found: (found, total) => `${total} paradan ${found} tanesi bulundu`,
      showPool: 'Tüm paraları göster',
      hidePool: 'Gizle',
      rolled: '{name} — {tier} çıktı.',
      backupTitle: 'Koleksiyonunu başka bir tarayıcıya taşı',
      backupIntro:
        'Çektiklerin yalnızca bu tarayıcıda tutulur; temizlersen ya da telefon değiştirirsen kaybolur. Aşağıdaki kodu kopyala, bir yere kaydet ve diğer cihazda buraya yapıştır.',
      backupCopy: 'Kodumu kopyala',
      backupRestore: 'Bir koddan geri yükle',
      backupFieldLabel: 'Koleksiyon kodun',
      backupPlaceholder: 'Geri yüklemek için buraya bir kod yapıştır',
      backupCopied: 'Kopyalandı. Güvenli bir yerde sakla.',
      backupSelected: 'Seçildi — kendin kopyala.',
      backupBad: 'Bu bir koleksiyon kodu değil.',
      backupRestored: 'Geri yüklendi. {count} coinin var.',
      locked: 'Henüz bulunmadı',
      download: 'PNG indir',
      shareCard: 'Kartı paylaş',
      postOnX: "X'te paylaş",
      shareText: (name, tier) => `${name} çektim — ${tier}.\n\nYa bu seninkiyse?`,
      odds: 'olasılık',
      openGenerator: 'Kendi paranı çek',
    },
    ask: {
      dailyArchiveTitle: 'Bugüne kadarki her gün',
      dailyArchiveIntro: 'Günde bir soru, herkese aynısı. Hepsi burada.',
      dailyAnswerCta: 'Buna cevap ver',
      title: 'Daha iyi bir soru sor',
      eyebrow: 'Üretici',
      heading: { lead: 'Ya', accent: 'her şey mümkünse?' },
      intro:
        'Bütün coin tek bir sorudan ibaret. İşte o soru, tekrar tekrar, ve neredeyse hiç aynısı çıkmadan.',
      again: 'Bir tane daha',
      copyLink: 'Bağlantıyı kopyala',
      copied: 'Kopyalandı.',
      linkCopied: 'Bağlantı kopyalandı.',
      today: 'Bugünün sorusu',
      answerLabel: 'Senin cevabın',
      answerPlaceholder: 'Ne düşündüğünü yaz. Kartın üstüne geçer.',
      postOnX: "X'te paylaş",
      download: 'Kartı indir',
      possibilities: 'olası soru',
      hint: 'yenisi için boşluğa bas',
      shareText: '{question}\n\nHâlâ soruyoruz.',
    },
    learn: {
      title: 'Öğren',
      eyebrow: 'Öğren',
      heading: { lead: 'Ne yaptığını', accent: 'bil.' },
      intro:
        'Bunun nasıl işlediği, paranı nasıl güvende tutacağın ve bu sitedeki her iddiayı kendin nasıl kontrol edeceğin. Önce güvenlik.',
      backToIndex: 'Tüm sayfalar',
      next: 'Sonraki:',
      previous: 'Önceki:',
      categories: { safety: 'Güvende kal', basics: 'Temeller', token: 'Bu token' },
      updatedLabel: 'Güncellendi',
    },
    roadmap: {
      title: 'Yol haritası',
      eyebrow: 'Yol haritası',
      heading: { lead: 'Ne yapıldı,', accent: 'sırada ne var.' },
      intro:
        'Yayına alınan her şey bu sayfada kalır. Yalnızca geleceği gösteren bir yol haritası, dilek listesidir.',
      open: 'Bir bak',
      statuses: {
        building: 'Şu anda yapılıyor',
        next: 'Sırada',
        later: 'Daha sonra',
        shipped: 'Yayına alındı',
      },
      shippedCount: 'şey yayına alındı',
      note: 'Henüz gerçekleşmemiş hiçbir şey için tarih verilmiyor. Bu bir meme coin ve tarih, kriptoda tutulması en kolay bozulan sözdür — yayına alınanlarda tarih var, çünkü onlar zaten oldu.',
    },
    holdings: {
      title: 'Cüzdan sorgusu',
      eyebrow: 'Senin çantan',
      heading: { lead: 'Ya bir', accent: 'baksaydın?' },
      intro:
        'Herhangi bir adresi yapıştır, ne tuttuğunu gör. Cüzdan bağlamak yok, imza yok, onaylanacak hiçbir şey yok.',
      inputLabel: 'Cüzdan adresi',
      check: 'Sorgula',
      privacy:
        'Bakiye, herkese açık bir defterdeki herkese açık veridir; burada yapılan sadece onu okumak — bir blok gezgininin yaptığının aynısı. Adresi sen yazıyorsun, hiçbir cüzdandan istenmiyor. Hiçbir şey saklanmıyor ve zincir dışında hiçbir yere bir şey gönderilmiyor.',
      download: 'Kartı indir',
      postOnX: "X'te paylaş",
      shareText: '{tokens} {symbol} tutuyorum.\n\nHâlâ soruyoruz.',
      bands: {
        whale: 'Balina',
        shark: 'Köpekbalığı',
        holder: 'Sahip',
        curious: 'Meraklı',
        empty: 'Boş',
      },
      verdicts: {
        whale: 'Sen kımıldayınca grafik kımıldıyor.',
        shark: 'İşte buna pozisyon denir.',
        holder: 'İçindesin. Hem de tam anlamıyla.',
        curious: 'Başlamak da başlamaktır.',
        empty: 'Burada henüz hiçbir şey yok. Ya bu değişseydi?',
      },
      errors: {
        empty: 'Önce bir adres yapıştır.',
        ens: 'Bu tür isimler Robinhood Chain üzerinde çözümlenmiyor. 0x adresini kullan.',
        txHash: "Bu bir işlem hash'i gibi görünüyor, adres değil — iki katı uzunlukta.",
        prefix: 'Adresler 0x ile başlar.',
        shape: 'Bu geçerli bir adres değil. Adresler 42 karakterdir ve 0x ile başlar.',
        network: 'Şu anda zincire ulaşılamadı. Birazdan tekrar dene.',
      },
    },
    notFound: {
      title: 'Sayfa bulunamadı',
      eyebrow: '404',
      heading: { lead: 'Ya bu sayfa', accent: 'hiç var olmadıysa?' },
      intro: 'Olmadı. Burada hiçbir şey taşınmadı — bu adres hiçbir zaman bizim olmadı.',
      tryThese: 'Bunlar gerçekten var',
    },
    meme: {
      intro: 'Tam çözünürlük, filigran yok, kaynak göstermeye gerek yok. Al götür.',
      description: (title, series) =>
        `${title} — ${series} serisinden bir $IF meme. Tam çözünürlük, serbestçe paylaş, kaynak gerekmez.`,
      download: 'İndir',
      postOnX: "X'te paylaş",
      more: 'Serinin devamı:',
      backToVault: 'Kasaya dön',
      shareText: (title) => `${title}\n\nHâlâ soruyoruz.`,
    },
  },

  common: {
    skipToContent: 'İçeriğe geç',
    externalLink: 'yeni sekmede açılır',
  },
};
