import type { SiteCopy } from './types.ts';

export const zh: SiteCopy = {
  htmlLang: 'zh-CN',

  nav: {
    links: [
      { label: '核心理念', href: '#thesis' },
      { label: '数据', href: '#numbers' },
      { label: '如何购买', href: '#buy' },
      { label: '常见问题', href: '#faq' },
    ],
    toolsLabel: '工具',
    tools: {
      ask: { label: '问一个更好的问题', blurb: '一百万种发问方式' },
      pfp: { label: '找到你的币', blurb: '四种稀有度，总有一枚是你' },
      memes: { label: '迷因库', blurb: '随便拿' },
      stats: { label: '数据', blurb: '每个数字都是实时的' },
      holdings: { label: '钱包查询', blurb: '无需连接' },
      learn: { label: '了解', blurb: '安全、基础与证据' },
      docs: { label: '白皮书', blurb: '完整内容，白纸黑字' },
      roadmap: { label: '更新', blurb: '最新的变化' },
      brand: { label: '品牌', blurb: '标识与素材' },
    },
    toolGroups: { data: '数据', play: '玩玩看', assets: '素材', read: '阅读' },
    languageMenu: '语言',
    buy: '购买 $IF',
    home: 'What $IF — 首页',
    pfp: '找到你的币',
    openMenu: '打开菜单',
    closeMenu: '关闭菜单',
    languageLabel: '语言',
  },

  hero: {
    liveOn: '已在 Robinhood Chain 上线',
    titleLead: '如果',
    titleTail: '这就是那一个？',
    description:
      '为永远好奇的人打造的迷因币。如果你早点买入会怎样？如果你一直持有会怎样？如果这就是那一个会怎样？',
    buy: '购买 $IF',
    chart: '图表',
  },

  posts: {
    eyebrow: '来自时间线',
    readOnX: '在 X 上查看',
    heading: { lead: '大家还在', accent: '问。' },
    intro: '社区正在发布的内容。在这里呈现，而不是嵌入 —— 没有追踪器，没有 iframe。',
    follow: '在 X 上关注',
  },

  marquee: [
    '如果 $IF',
    '你早点买入？',
    '如果',
    '你一直持有？',
    '如果',
    '这就是那一个？',
    '如果',
    '我们从不卖出？',
    '如果',
    '它冲上十亿？',
  ],

  cosmic: {
    kicker: '如果',
    statements: [
      '如果我能拯救一条生命？',
      '如果我能用一个愿望治愈癌症？',
      '如果爱比我们所有人都长久？',
      '如果一个声音能终结一场战争？',
      '如果破碎的人成为了建造者？',
      '如果希望从来不是谎言？',
      '如果一个孩子的梦想改写了明天？',
      '如果仁慈比权力更强大？',
      '如果我们记得每一个名字？',
      '如果最黑暗的夜里藏着黎明？',
      '如果宽恕就是解药？',
      '如果没有人独自悲伤？',
    ],
  },

  thesis: {
    eyebrow: '核心理念',
    heading: { lead: '一个问题。', accent: '无限可能。' },
    intro:
      '$IF 不是实用型代币，也不是治理代币。它是每个人凌晨三点都会冒出的那个念头，被铸造在了这条最新的公链上。',
    pillars: [
      {
        title: '一切始于一个问题',
        body: '你后悔过的每一笔交易，都始于「如果当初」。$IF 只是认真到把这个问题放上了链。',
      },
      {
        title: '构建于 Robinhood Chain',
        body: '出块快、手续费低，还有那个把一代人拉进市场的名字。Robinhood 当初也是一个「如果」。',
      },
      {
        title: '9% 已经消失',
        body: '{burned} 枚 $IF（占供应量 {burnedPercent}）躺在一个没有人持有私钥的销毁地址里。这不是承诺——这是一个你可以自己去读的余额。',
      },
      {
        title: '一切自己核实',
        body: '合约、流动性池、销毁记录和持有人数量全部公开，我们把每一个都附上了链接。不要相信任何网站——包括这一个。',
      },
    ],
  },

  numbers: {
    eyebrow: '数据',
    heading: { lead: '没有套路。', accent: '只有数字。' },
    intro: '十亿枚代币、一份公开合约，以及一个任何人都能审计的销毁地址。所以这一节很短。',
    contractLabel: '合约地址',
    verifyNote: '购买前请对照我们的 X 和 Telegram，逐个字符核对。',
    copy: '复制',
    copied: '已复制',
    viewOnExplorer: '在 Blockscout 查看',
    stats: {
      price: '价格',
      marketCap: '市值',
      liquidity: '流动性',
      volume: '24 小时成交量',
      supply: '总供应量',
      burned: '已销毁',
      holders: '持有人',
      chain: '公链',
    },
    burnHeadline: '已销毁且无法找回',
    burnBody:
      '发送到 0x…dEaD —— 一个没有私钥的地址。没有人能再动这些代币，团队不能，你不能，任何人都不能。',
    asOf: '截至',
    live: '实时',
  },

  buy: {
    eyebrow: '上车',
    heading: { lead: '三步。', accent: '就这么多。' },
    intro: '你需要一个钱包、一点在 Robinhood Chain 上的 ETH，以及三十秒。全部流程如下。',
    steps: [
      {
        title: '准备钱包',
        body: '电脑上用 MetaMask、OKX 或 Trust，手机上用 Robinhood Wallet。第一次访问用到 Robinhood Chain 的页面时，钱包会引导你添加该网络。',
        action: '获取 MetaMask',
      },
      {
        title: '把 ETH 转到 Robinhood Chain',
        body: '在 Robinhood App 中提取 ETH 并选择 Robinhood Chain 网络。ETH 在别的链上？Robinhood 官方文档列出了跨链路径。',
        action: '跨链指南',
      },
      {
        title: '在 Uniswap 兑换',
        body: '打开时已在 Robinhood Chain 上预选 $IF。确认交易前，请把那个页面上的地址和上面的地址对一遍。',
        action: '在 Uniswap 兑换',
      },
    ],
    venuesTitle: '追踪、看图、核实',
    venues: [
      { label: 'Uniswap', blurb: '主要的 IF/WETH 流动性池。' },
      { label: 'DexScreener', blurb: '实时价格与流动性。' },
      { label: 'CoinGecko', blurb: '市场数据与历史。' },
      { label: 'CoinMarketCap', blurb: '排名与供应量。' },
      { label: 'Blockscout', blurb: '合约本身。' },
    ],
    safetyNote:
      '本站永远不会要求你连接钱包、签名或输入助记词。如果有页面自称 $IF 并这样要求，那不是我们。',
  },

  pfpTeaser: {
    eyebrow: '币池',
    heading: { lead: '找到属于', accent: '你的那一枚。' },
    body: '手工制作的 $IF 币，四种稀有度。点一下就能获得，直接用作头像。无需钱包、无需注册、无需连接任何东西。',
    cta: '打开生成器',
  },

  vaultTeaser: {
    eyebrow: '迷因库',
    heading: { lead: '每一张迷因图。', accent: '随便拿。' },
    body: '我们做过的每一张迷因图，全分辨率，随时可发。它们本来就是为此而生的。请负责任地右键保存。',
    cta: '打开迷因库',
  },

  roadmap: {
    eyebrow: '投资者总在问',
    heading: { lead: '那么…', accent: '路线图呢？' },
    fileName: 'if_roadmap_final_v3.pdf',
    lastEdited: '1 页 · 上次编辑：从未',
    quarters: ['Q1 —— 如果', 'Q2 —— 如果', 'Q3 —— 还在问', 'Q4 —— 大概是迷因'],
    stamp: '还在问。',
    footnote: '没有路线图，没有实用功能，没有承诺。仅供娱乐。',
  },

  faq: {
    eyebrow: '没有蠢问题',
    heading: { lead: '问题，', accent: '已解答。' },
    items: [
      {
        q: '$IF 是什么？',
        a: '$IF 是 Robinhood Chain 上的一枚迷因币，围绕每个交易者凌晨三点都会问自己的那个问题打造：如果当初会怎样？没有产品路线图，也没有实用功能。有的是一个问题、一个社区和一张图表。',
      },
      {
        q: '怎么把 ETH 转到 Robinhood Chain？',
        a: '这是大多数新手卡住的地方。最简单的方式是在 Robinhood App 里提取 ETH 并选择 Robinhood Chain 网络。如果你的 ETH 在别的链上，Robinhood 官方文档列出了可用的跨链桥。无论哪种方式，都要留一点 ETH 付手续费。',
      },
      {
        q: '在哪里购买？',
        a: '在 Robinhood Chain 上的 Uniswap，使用本页的合约地址。深度最好的是 IF/WETH 池。请务必逐字符核对地址——迷因币总会引来仿冒者，一个字符错了，钱就进了陌生人的口袋。',
      },
      {
        q: '怎么确认拿到的是正确的代币？',
        a: '我们唯一会公布的地址是 0x232CDFc415D10b673845D83Dc02ba2eaBe7e30d1，它会完整地出现在本页、我们的 X 主页和 Telegram 上。如果某个网站给你看的是缩写版或另一个地址，请立刻关掉。',
      },
      {
        q: '有交易税吗？',
        a: '$IF 合约不会在你的交易之外额外收取任何费用。你在主池看到的 1% 是 Uniswap 自己的费率档位，归提供流动性的人所有，不归我们。合约在 Blockscout 上公开——请自己去读，而不是相信一个网站的说法。',
      },
      {
        q: '销毁了多少？',
        a: '{burned} 枚 $IF（占总供应量 {burnedPercent}）位于 0x…dEaD，一个没有私钥的地址。这些代币永远无法再被转移。这是区块浏览器上的实时余额，不是文件里的一句承诺。',
      },
      {
        q: '社区在哪里？',
        a: 'X 是 @WhatIFonHOOD，Telegram 是 t.me/WhatIFonHoodChain。两个都很活跃，都由持币的人自己在运营。每个人都是开发者。',
      },
      {
        q: '$IF 是一项投资吗？',
        a: '不是。它是一枚没有内在价值、没有团队承诺、没有路线图的迷因币。价格下跌和上涨一样容易，绝大多数迷因币最终归零。永远不要投入超过你能坦然承受全部损失的金额。',
      },
    ],
  },

  footer: {
    heading: { lead: '如果你加入了', accent: '会怎样？' },
    subtitle: '图表就在那里。问题就在这里。',
    buy: '购买 $IF',
    telegram: '加入 Telegram',
    follow: '在 X 上关注',
    chart: '图表',
    canonical: '唯一的官方网站是 whatifonhood.com，其他都不是我们。',
    disclaimer:
      '$IF 是一枚没有内在价值、也不应期待任何财务回报的迷因币。本站内容不构成投资建议。请自行研究（DYOR）。',
    builtBy: '每个人都是开发者。',
  },

  pages: {
    memes: {
      title: '迷因库',
      heading: { lead: '每一张迷因图。', accent: '随便拿。' },
      intro:
        '每一张 $IF 迷因图，全分辨率，无水印，无需署名。发它、印它、改它——它们本来就是为此而生的。',
      download: '下载',
      all: '全部',
      searchLabel: '搜索迷因',
      empty: '没有匹配的结果，换个词试试。',
      count: '张',
    },
    brand: {
      title: '品牌',
      heading: { lead: '三个标识，', accent: '以及用法。' },
      intro: '一个品牌，三个标识：币标识代币，角色标识世界，字标标识名字。需要什么就拿什么。',
      download: '下载',
      kitNote: '包含标识、头像、矢量字标、横幅、角色参考图和透明素材——附带调色板、字体与使用说明。',
      rulesTitle: '三条重要规则',
      rules: [
        '硬币必须保留外圈，这是它之所以像一枚货币的原因。',
        '合约地址不要使用展示字体，也不要缩写。',
        '不要使用 Robinhood 的羽毛标识，改为写「on Robinhood Chain」。',
      ],
    },
    stats: {
      title: '数据',
      heading: { lead: '每一个数字，', accent: '都是实时的。' },
      intro: '价格、流动性、供应量与销毁——直接读自 Robinhood Chain。',
      sourceNote:
        '价格、流动性和成交量来自 DexScreener；持有者和集中度来自 GeckoTerminal；销毁数据直接读自链上。只要这个标签页开着，一切都会自动刷新。',
      poolLabel: '主要流动性池',
      openExplorer: '打开合约',
      openChart: '打开图表',
      timeframes: { day: '24小时', week: '7天', month: '30天', quarter: '90天', all: '全部' },
      resizeChart: '拖动以调整图表高度',
      zoomIn: '放大',
      zoomOut: '缩小',
      resetZoom: '重置',
      average: '均线',
      ema: 'EMA',
      chartHint: '滚轮缩放 · 拖动平移 · 双击重置',
      chartTypes: { candles: 'K线', line: '折线' },
      logScale: '对数',
      chartTitle: '价格',
      feedTitle: '最新成交',
      biggestBuy: '最大买单',
      buys: '买入',
      sells: '卖出',
      buyLabel: '买',
      sellLabel: '卖',
      viewTx: '查看',
      loading: '正在读取链上数据…',
      failed: '暂时无法获取行情数据，以上数字来自最近一次构建。',
      feedNote: 'IF/WETH 池的最新成交记录。',
      biggestSell: '最大卖出',
      windowHours: '过去 {hours} 小时内',
      holdersTitle: '持有者',
      concentration: '谁在持有',
      bands: { top10: '前 10', next20: '11–30', next20More: '31–50', rest: '其余所有人' },
      holdersUpdated: '重新统计于',
      pressureTitle: '买卖压力',
      pressureNote: '过去一天的每小时成交量，仅统计 500 美元以上的交易。买入向上，卖出向下。',
      burnHistoryTitle: '每一次销毁',
      burnHistoryNote: '直接读自链上。每一级台阶都是一笔可以打开的交易。',
      reproduceTitle: '自己核对每一个数字',
      reproduceIntro:
        '本页每一个数字都来自公开、无需密钥的只读调用。以下是我们实际发出的每一条请求，复制到终端即可运行。',
      reproduceField: '数字位于',
      reproduceNote:
        '这些命令由页面本身使用的同一组地址和端点生成，因此不会悄悄失效。如果某条结果与上方显示的不一致，那就是页面错了，请告诉我们。',
      reproduceLabels: {
        price: '价格',
        marketCap: '市值',
        liquidity: '流动性',
        volume: '24 小时成交量',
        holders: '持币地址数',
        burned: '已销毁代币',
        supply: '总供应量',
        owner: '谁能修改合约',
        trades: '近期交易',
        holderList: '最大持有者',
      },
      weekTitle: '过去七天',
      weekPrice: '价格',
      weekBurned: '已销毁',
      weekBurnCount: '共 {count} 次销毁',
      weekLargest: '单笔最大销毁',
      weekNote: '截至 {date}。每日更新，非实时 —— 上方的数据才是实时的。',
      holderTableTitle: '谁持有',
      holderTableIntro:
        '持仓最大的十五个地址，能识别的都已标注。最大的是销毁地址 —— 那些代币已经销毁，不是被持有。',
      holderTableNote: '{date} 从区块浏览器读取。每一行都链接到该地址。',
      holderAddress: '地址',
      holderWhat: '这是什么',
      holderTokens: '代币数量',
      holderShare: '占总量比例',
      holderKinds: { burn: '已销毁', pool: '流动性池', contract: '合约', unknown: '—' },
      biggestBurnsTitle: '最大的十次销毁',
      sinceLead: '自你上次来访，{ago}',
      sincePrice: '价格变动 {change}，现为 {price}。',
      sinceBurned: '销毁了 {amount} $IF。',
      sinceHolders: '持币地址 {change}，现为 {total}。',
      sinceNothing: '没什么变化。依然在问。',
      trustTitle: '任何人都能做的核查',
      trustNote:
        '其中两项由第三方认证，不是我们说的；另外三项由本页面在加载时直接从合约读取。每一项都链接到你可以自行核查的地方，读取不到的项会如实说明，而不是显示通过。',
      checks: {
        verified: '上市已验证',
        honeypot: '蜜罐检测',
        supply: '固定供应量，无增发函数',
        burn: '销毁地址没有私钥',
        owner: '谁能修改合约',
      },
      checkPass: '通过',
      burnMark: '销毁 {amount}',
      ownerNone: '没有 owner 函数',
      ownerSome: '所有者',
    },
    pfp: {
      title: '头像生成器',
      heading: { lead: '找到属于', accent: '你的那一枚。' },
      intro: '点击生成，拿到一枚 $IF 硬币，设为头像。无需钱包、无需注册、无需连接任何东西。',
      subline: '四种稀有度，每次抽取免费。',
      generate: '生成我的 $IF',
      again: '再来一次',
      hint: '一键完成。所有记录只保存在你自己的浏览器里。',
      tiers: { common: '普通', uncommon: '罕见', rare: '稀有', legendary: '传说' },
      found: (found, total) => `已收集 ${found} / ${total}`,
      showPool: '查看全部硬币',
      hidePool: '收起',
      rolled: '你抽到了 {name} — {tier}。',
      backupTitle: '把你的收藏带到另一个浏览器',
      backupIntro:
        '你抽到的内容只保存在这个浏览器里，清除数据或换手机就会丢失。复制下面的代码保存好，在另一台设备上粘贴回来即可。',
      backupCopy: '复制我的代码',
      backupRestore: '用代码恢复',
      backupFieldLabel: '你的收藏代码',
      backupPlaceholder: '在此粘贴代码以恢复',
      backupCopied: '已复制。请妥善保存。',
      backupSelected: '已选中 —— 请自行复制。',
      backupBad: '这不是收藏代码。',
      backupRestored: '已恢复。你有 {count} 枚。',
      locked: '尚未获得',
      download: '下载 PNG',
      shareCard: '分享卡片',
      postOnX: '发到 X',
      shareText: (name, tier) => `我抽到了 ${name} —— ${tier}。\n\n如果这一枚就是你呢？`,
      odds: '概率',
      openGenerator: '抽你自己的',
    },
    ask: {
      dailyArchiveTitle: '至今的每一天',
      dailyArchiveIntro: '每天一个问题，所有人都一样。这里是全部。',
      dailyAnswerCta: '回答这一个',
      title: '问一个更好的问题',
      eyebrow: '生成器',
      heading: { lead: '如果', accent: '什么都有可能？' },
      intro: '整个币就是一个问题。这里一遍又一遍地问，而且几乎不会重复。',
      again: '再来一个',
      copyLink: '复制链接',
      copied: '已复制。',
      linkCopied: '链接已复制。',
      today: '今天的问题',
      answerLabel: '你的回答',
      answerPlaceholder: '说说你的想法，它会出现在卡片上。',
      postOnX: '发到 X',
      download: '下载卡片',
      possibilities: '种可能的问题',
      hint: '按空格换一个',
      shareText: '{question}\n\n还在问。',
    },
    learn: {
      title: '了解',
      eyebrow: '了解',
      heading: { lead: '搞清楚你在', accent: '做什么。' },
      intro: '这一切是怎么运作的、如何保护好你的钱，以及如何自己核实本站的每一项说法。安全第一。',
      backToIndex: '全部页面',
      next: '下一篇：',
      previous: '上一篇：',
      categories: { safety: '保护自己', basics: '基础知识', token: '这个代币' },
      updatedLabel: '更新于',
    },
    roadmap: {
      title: '路线图',
      eyebrow: '路线图',
      heading: { lead: '做完了什么，', accent: '接下来做什么。' },
      intro: '所有已上线的内容都留在这个页面上。只展示未来的路线图，那叫愿望清单。',
      open: '去看看',
      statuses: {
        building: '正在做',
        next: '接下来',
        later: '以后',
        shipped: '已经上线',
      },
      shippedCount: '项已经上线',
      note: '对还没发生的事情，这里不承诺任何日期。这是一枚迷因币，而日期是加密世界里最容易被打破的承诺 —— 已上线的条目有日期，因为那些已经发生了。',
    },
    holdings: {
      title: '钱包查询',
      eyebrow: '你的仓位',
      heading: { lead: '如果你', accent: '查一下呢？' },
      intro: '粘贴任意地址，看看它持有多少。无需连接钱包，无需签名，没有任何需要授权的东西。',
      inputLabel: '钱包地址',
      check: '查询',
      privacy:
        '余额是公开账本上的公开数据，所以这只是把它读出来 —— 和区块浏览器做的事情一样。地址由你自己输入，绝不会向钱包索取。不保存任何内容，除了链上查询之外不向任何地方发送数据。',
      download: '下载卡片',
      postOnX: '发到 X',
      shareText: '我持有 {tokens} {symbol}。\n\n还在问。',
      bands: { whale: '巨鲸', shark: '大户', holder: '持有者', curious: '好奇者', empty: '空仓' },
      verdicts: {
        whale: '你一动，图就动。',
        shark: '这才叫仓位。',
        holder: '你在场，而且是认真的。',
        curious: '开始了就是开始了。',
        empty: '这里还什么都没有。如果这一点变了呢？',
      },
      errors: {
        empty: '请先粘贴一个地址。',
        ens: '这类域名在 Robinhood Chain 上无法解析，请使用 0x 地址。',
        txHash: '这看起来是交易哈希，不是地址 —— 长度多了一倍。',
        prefix: '地址以 0x 开头。',
        shape: '这不是有效的地址。地址是 42 个字符，以 0x 开头。',
        network: '暂时无法连接到链上，请稍后再试。',
      },
    },
    notFound: {
      title: '页面未找到',
      eyebrow: '404',
      heading: { lead: '如果这个页面', accent: '从未存在过？' },
      intro: '它确实不存在。这里什么都没有搬走 —— 这个地址从来就不是我们的。',
      tryThese: '这些是存在的',
    },
    meme: {
      intro: '最高分辨率，无水印，无需署名。拿走吧。',
      description: (title, series) =>
        `${title} —— 来自 ${series} 系列的 $IF 梗图。最高分辨率，随意发布，无需署名。`,
      download: '下载',
      postOnX: '发到 X',
      more: '更多来自',
      backToVault: '返回梗图库',
      shareText: (title) => `${title}\n\n还在问。`,
    },
  },

  common: {
    skipToContent: '跳到主要内容',
    externalLink: '在新标签页打开',
  },
};
