/**
 * Generates public/_headers and vercel.json from src/config/security-headers.ts.
 *
 * Run with `npm run headers`. Both files are committed; a test fails if either
 * stops matching the config, which is how a hand edit gets caught.
 *
 * The two hosts resolve conflicts in opposite directions — Netlify takes the
 * FIRST matching rule for a header, Vercel the LAST — so the specific rules are
 * emitted before the catch-all for Netlify and after it for Vercel. That is why
 * this generator exists rather than one shared list written twice.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  CANVAS_PATHS,
  CANVAS_POLICY,
  HTML_CACHE,
  IMMUTABLE_CACHE,
  IMMUTABLE_PATHS,
  SECURITY_HEADERS,
  SITE_POLICY,
  WEEK_CACHE,
  WEEK_PATHS,
} from '../src/config/security-headers.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

// ---------------------------------------------------------------- Netlify
const netlify = [
  '# Generated by tools/build-headers.mjs — do not edit by hand.',
  '# Edit src/config/security-headers.ts and run `npm run headers`.',
  '#',
  '# Netlify applies the FIRST matching rule for a given header, so the specific',
  '# paths come before the catch-all here. Vercel is the opposite; see the tool.',
  '',
];

for (const path of CANVAS_PATHS) {
  netlify.push(`${path}/*`, `  Content-Security-Policy: ${CANVAS_POLICY}`, '');
}
for (const path of IMMUTABLE_PATHS) {
  netlify.push(`${path}/*`, `  Cache-Control: ${IMMUTABLE_CACHE}`, '');
}
for (const path of WEEK_PATHS) {
  netlify.push(`${path}/*`, `  Cache-Control: ${WEEK_CACHE}`, '');
}
netlify.push('/*');
for (const [key, value] of SECURITY_HEADERS) netlify.push(`  ${key}: ${value}`);
netlify.push(`  Content-Security-Policy: ${SITE_POLICY}`, `  Cache-Control: ${HTML_CACHE}`, '');

writeFileSync(join(root, 'public', '_headers'), netlify.join('\n'));

// ---------------------------------------------------------------- Vercel
const vercel = JSON.parse(readFileSync(join(root, 'vercel.json'), 'utf8'));

vercel.headers = [
  {
    source: '/(.*)',
    headers: [
      ...SECURITY_HEADERS.map(([key, value]) => ({ key, value })),
      { key: 'Content-Security-Policy', value: SITE_POLICY },
      { key: 'Cache-Control', value: HTML_CACHE },
    ],
  },
  ...CANVAS_PATHS.map((path) => ({
    source: `${path}/(.*)`,
    headers: [{ key: 'Content-Security-Policy', value: CANVAS_POLICY }],
  })),
  ...IMMUTABLE_PATHS.map((path) => ({
    source: `${path}/(.*)`,
    headers: [{ key: 'Cache-Control', value: IMMUTABLE_CACHE }],
  })),
  ...WEEK_PATHS.map((path) => ({
    source: `${path}/(.*)`,
    headers: [{ key: 'Cache-Control', value: WEEK_CACHE }],
  })),
];

writeFileSync(join(root, 'vercel.json'), `${JSON.stringify(vercel, null, 2)}\n`);

process.stdout.write(
  `Wrote public/_headers and vercel.json — ${CANVAS_PATHS.length} canvas paths, ` +
    `${IMMUTABLE_PATHS.length} immutable, ${WEEK_PATHS.length} weekly\n`,
);
