/**
 * Builds the burn history from the chain itself.
 *
 * Every burn is a Transfer of $IF into 0x…dEaD, an address with no private key.
 * This walks the chain's logs backwards, collects each one, resolves the block
 * timestamps, and writes src/config/burns.ts.
 *
 * Run with `npm run burns`. The result is committed, so the page has the whole
 * history instantly and only has to ask the chain for anything newer.
 *
 * Why events and not balances: the public RPC is not an archive node. Asking it
 * for a past balance fails with "metadata is not found", so the curve has to be
 * built from the events that made it. That is the better answer anyway — every
 * step links to the transaction that caused it.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CHAIN, TOKEN } from '../src/config/site.ts';

const here = dirname(fileURLToPath(import.meta.url));
const output = resolve(here, '..', 'src', 'config', 'burns.ts');

/** keccak256("Transfer(address,address,uint256)") */
const TRANSFER = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const DEAD_TOPIC = `0x${TOKEN.burnAddress.slice(2).toLowerCase().padStart(64, '0')}`;

/**
 * Blocks per request.
 *
 * At roughly ten blocks a second this is about 28 hours of chain. Asking for
 * much more times the node out, so this number is load-bearing rather than
 * arbitrary.
 */
const CHUNK = 1_000_000;

/** Space requests out; the endpoint answers a bot challenge if you rush it. */
const PACE_MS = 250;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function rpc(method, params, attempt = 0) {
  await sleep(PACE_MS);
  try {
    const response = await fetch(CHAIN.rpcUrl, {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        accept: 'application/json',
        // Without this the endpoint serves a Cloudflare challenge to scripts.
        'user-agent':
          'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36',
      },
      body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
      signal: AbortSignal.timeout(30_000),
    });

    const text = await response.text();
    // A challenge page is HTML, not JSON. Treat it as "slow down", not as a bug.
    if (text.startsWith('<')) throw new Error('rate-limited');

    const body = JSON.parse(text);
    if (body.error) throw new Error(body.error.message);
    return body.result;
  } catch (error) {
    if (attempt < 6) {
      await sleep(1500 * 2 ** attempt);
      return rpc(method, params, attempt + 1);
    }
    throw error;
  }
}

const head = Number(await rpc('eth_blockNumber', []));
console.warn(`Head block ${head.toLocaleString()}, scanning back in ${CHUNK.toLocaleString()}-block chunks`);

const events = [];
for (let to = head; to > 0; to -= CHUNK) {
  const from = Math.max(0, to - CHUNK + 1);
  const logs = await rpc('eth_getLogs', [
    {
      fromBlock: `0x${from.toString(16)}`,
      toBlock: `0x${to.toString(16)}`,
      address: TOKEN.address,
      topics: [TRANSFER, null, DEAD_TOPIC],
    },
  ]);

  for (const log of logs ?? []) {
    events.push({
      block: Number(log.blockNumber),
      tx: log.transactionHash,
      // The amount is the single unindexed argument, so it is the whole data word.
      tokens: Number(BigInt(log.data) / 10n ** BigInt(TOKEN.decimals)),
    });
  }
  process.stdout.write(`\r  block ${from.toLocaleString().padStart(12)} — ${events.length} burns`);
}
process.stdout.write('\n');

// Timestamps come one block at a time, but burns are rare so this is cheap.
const blocks = [...new Set(events.map((event) => event.block))];
const times = new Map();
for (const [index, block] of blocks.entries()) {
  const found = await rpc('eth_getBlockByNumber', [`0x${block.toString(16)}`, false]);
  if (found) times.set(block, Number(found.timestamp));
  process.stdout.write(`\r  timestamps ${index + 1}/${blocks.length}`);
}
process.stdout.write('\n');

const rows = events
  .filter((event) => times.has(event.block) && event.tokens > 0)
  .map((event) => ({ time: times.get(event.block), tokens: event.tokens, tx: event.tx }))
  .sort((a, b) => a.time - b.time);

const total = rows.reduce((sum, row) => sum + row.tokens, 0);

writeFileSync(
  output,
  `// Generated by tools/build-burns.mjs — do not edit by hand.
// Run \`npm run burns\` to refresh. Every row is a Transfer into ${TOKEN.burnAddress},
// read from the chain's own logs, and links to the transaction that made it.

export interface BurnEvent {
  /** Unix seconds. */
  time: number;
  /** Whole $IF, floored. */
  tokens: number;
  txHash: string;
}

/** Oldest first. */
export const BURNS: BurnEvent[] = ${JSON.stringify(
    rows.map((row) => ({ time: row.time, tokens: row.tokens, txHash: row.tx })),
    null,
    2,
  )};

/** Block this history was scanned to; the page asks the chain for anything after. */
export const BURNS_SCANNED_TO = ${head};
`,
);

console.warn(
  `${rows.length} burns written, ${Math.round(total).toLocaleString()} $IF total`,
);
