/**
 * Builds the meme vault from the brand pack.
 *
 * Reads every PNG in the meme pack, writes a 640px thumbnail and a
 * full-resolution WebP into public/memes/, and regenerates
 * src/config/memes.ts so the gallery page always matches what is on disk.
 *
 * To add a meme: drop the PNG into the meme pack and run `npm run memes`.
 *
 * Requires ImageMagick 7 (`brew install imagemagick`).
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const source = resolve(root, '..', 'what-if-meme', 'brand-pack', 'meme-pack', 'memes');
const thumbDir = join(root, 'public', 'memes', 'thumb');
const thumb2xDir = join(root, 'public', 'memes', 'thumb2x');
const fullDir = join(root, 'public', 'memes', 'full');

// Two thumbnail widths, offered through a srcset: a phone showing two columns
// needs ~380 device pixels, a retina desktop showing four needs ~600. Serving
// one size for both means every phone downloads twice what it can display.
const THUMB_WIDTH = 400;
const THUMB_2X_WIDTH = 800;
const THUMB_QUALITY = 72;
const FULL_QUALITY = 82;

/**
 * Which series a meme belongs to, from its filename prefix. Series are how the
 * vault is filtered, and they mirror the lanes in MEME-CONCEPT-BANK.md.
 */
function seriesFor(slug) {
  if (slug.startsWith('gm-')) return 'gm';
  if (slug.startsWith('meme-figure-')) return 'Figures';
  if (slug.startsWith('meme-token-')) return 'Crossovers';
  if (slug.startsWith('meme-reactive-')) return 'Market days';
  if (slug.startsWith('meme-when-')) return 'The impostor';
  if (slug.startsWith('top-of-hood-')) return 'Summit';
  return 'Classics';
}

/** "meme-timeline-sold-vs-held" -> "Timeline sold vs held" */
function titleFor(slug) {
  const words = slug
    .replace(/^(meme|gm)-/, '')
    .replace(/^(figure|token|reactive|when)-/, '')
    .split('-');
  const joined = words.join(' ');
  return joined.charAt(0).toUpperCase() + joined.slice(1);
}

function dimensionsOf(file) {
  const output = execFileSync('magick', ['identify', '-format', '%w %h', file]).toString();
  const [width, height] = output.trim().split(' ').map(Number);
  return { width, height };
}

rmSync(join(root, 'public', 'memes'), { recursive: true, force: true });
mkdirSync(thumbDir, { recursive: true });
mkdirSync(thumb2xDir, { recursive: true });
mkdirSync(fullDir, { recursive: true });

const files = readdirSync(source)
  .filter((name) => name.endsWith('.png'))
  .sort();

const entries = [];

for (const [index, file] of files.entries()) {
  const slug = file.replace(/\.png$/, '');
  const input = join(source, file);
  const { width, height } = dimensionsOf(input);

  for (const [width, directory] of [
    [THUMB_WIDTH, thumbDir],
    [THUMB_2X_WIDTH, thumb2xDir],
  ]) {
    execFileSync('magick', [
      input,
      '-resize',
      `${width}x${width}>`,
      '-quality',
      String(THUMB_QUALITY),
      '-strip',
      join(directory, `${slug}.webp`),
    ]);
  }

  execFileSync('magick', [
    input,
    '-quality',
    String(FULL_QUALITY),
    '-strip',
    join(fullDir, `${slug}.webp`),
  ]);

  entries.push({ slug, title: titleFor(slug), series: seriesFor(slug), width, height });
  process.stdout.write(`\r  ${index + 1}/${files.length} ${slug.padEnd(44)}`);
}

const seriesOrder = [
  'Classics',
  'Crossovers',
  'Figures',
  'Market days',
  'The impostor',
  'gm',
  'Summit',
];
const seriesPresent = seriesOrder.filter((name) => entries.some((entry) => entry.series === name));

const output = `// Generated by tools/build-memes.mjs — do not edit by hand.
// Add a PNG to what-if-meme/brand-pack/meme-pack/memes and run \`npm run memes\`.

export interface Meme {
  /** File name without extension; also the thumbnail and download file name. */
  slug: string;
  title: string;
  series: string;
  width: number;
  height: number;
}

/** Every series in the vault, in display order. */
export const MEME_SERIES = ${JSON.stringify(seriesPresent)} as const;

export const MEMES: Meme[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(join(root, 'src', 'config', 'memes.ts'), output);
process.stdout.write(`\n${entries.length} memes written\n`);
