/**
 * Reads the largest holders from the block explorer.
 *
 * The single most common question about any token is "does one wallet hold all
 * of it". The honest answer needs the actual list, and it needs the top entries
 * labelled — the biggest holder here is the burn address, which is the opposite
 * of a whale, and the third is the liquidity pool everybody trades against.
 * Unlabelled, both look alarming.
 *
 * This runs at build time, not in the browser: the explorer sits behind a
 * Cloudflare challenge and sends no CORS header, so a page cannot call it. The
 * result is committed to src/config/holders.ts and refreshed by the daily job.
 *
 * Run with `npm run holders`.
 */

import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

import { CHAIN, TOKEN } from '../src/config/site.ts';

import { writeConfig } from './lib/write-config.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** How many rows to keep. Enough to show the shape without a wall of hashes. */
const KEEP = 15;

// The explorer refuses a bare script. This is the same pacing the RPC needs.
const BROWSER_UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

const response = await fetch(`${CHAIN.explorerUrl}/api/v2/tokens/${TOKEN.address}/holders`, {
  headers: { accept: 'application/json', 'user-agent': BROWSER_UA },
  signal: AbortSignal.timeout(30_000),
});
if (!response.ok) throw new Error(`explorer returned ${response.status}`);

const body = await response.json();
if (!Array.isArray(body.items)) throw new Error('explorer returned no holder list');

/**
 * The pools this token trades in, so they can be labelled as such.
 *
 * Read from DexScreener rather than hardcoded: a new pool should be named
 * "liquidity pool" the day it appears, not the next time someone edits a file.
 */
const pools = new Set();
try {
  const pairs = await fetch(`https://api.dexscreener.com/latest/dex/tokens/${TOKEN.address}`, {
    signal: AbortSignal.timeout(20_000),
  }).then((r) => r.json());
  for (const pair of pairs?.pairs ?? []) {
    if (typeof pair.pairAddress === 'string') pools.add(pair.pairAddress.toLowerCase());
  }
} catch {
  // The explorer already names most pool contracts; this only adds to that.
}

const DECIMALS = 10n ** BigInt(TOKEN.decimals ?? 18);

const holders = body.items.slice(0, KEEP).map((item) => {
  const address = String(item?.address?.hash ?? '');
  if (!/^0x[a-fA-F0-9]{40}$/.test(address)) {
    throw new Error(`the holder list carried a malformed address: ${address}`);
  }
  const tokens = Number(BigInt(item?.value ?? 0) / DECIMALS);
  const lower = address.toLowerCase();

  // What this address is, as far as anything can be established. Anything not
  // identified stays unlabelled rather than guessed at.
  let kind = 'unknown';
  if (lower === TOKEN.burnAddress.toLowerCase()) kind = 'burn';
  else if (pools.has(lower) || /pool|pair/i.test(item?.address?.name ?? '')) kind = 'pool';
  else if (item?.address?.is_contract) kind = 'contract';

  return { address, tokens, kind };
});

if (holders.length === 0) throw new Error('explorer returned an empty holder list');

const file = `// Generated by tools/build-holders.mjs — do not edit by hand.
// Run \`npm run holders\` to refresh. Read from the block explorer, which the
// browser cannot call directly: it is behind a challenge and sends no CORS header.

/** What an address is, when that can be established from the chain. */
export type HolderKind = 'burn' | 'pool' | 'contract' | 'unknown';

export interface Holder {
  address: string;
  /** Whole $IF, floored. */
  tokens: number;
  kind: HolderKind;
}

/** Largest first. */
export const HOLDERS: Holder[] = ${JSON.stringify(holders, null, 2)};

/** When this list was read, as YYYY-MM-DD. */
export const HOLDERS_CAPTURED = '${new Date().toISOString().slice(0, 10)}';
`;

await writeConfig(join(root, 'src', 'config', 'holders.ts'), file);
console.warn(
  `Wrote ${holders.length} holders — ` +
    `${holders.filter((h) => h.kind !== 'unknown').length} identified.`,
);
